#!/bin/bash

# ============================================================================
# SandboxFusion Router Startup Script
# ============================================================================
# This script generates config.yaml from a server list and starts the router.
#
# Usage:
#   1. Edit SERVERS array below with your server hostnames
#   2. Run: bash start_router.sh
#
# Example:
#   SERVERS=("node1" "node2" "node3")
#   → Generates URLs: http://node1:8080, http://node2:8080, http://node3:8080
# ============================================================================

# Configuration
SERVERS=(
    "server1"
    "server2"
    "server3"
)

PROTOCOL="http"
PORT="8080"
HEALTH_CHECK_INTERVAL=30
TIMEOUT=300
ROUTING_STRATEGY="round_robin"  # or "random"

ROUTER_HOST="0.0.0.0"
ROUTER_PORT="8000"

# ============================================================================
# Generate config.yaml
# ============================================================================

echo "Generating config.yaml from server list..."

cat > config.yaml <<EOF
# SandboxFusion Router Configuration
# Auto-generated by start_router.sh

# List of worker servers
workers:
EOF

# Add each server as a worker
for server in "${SERVERS[@]}"; do
    url="${PROTOCOL}://${server}:${PORT}"
    echo "  - url: ${url}" >> config.yaml
done

cat >> config.yaml <<EOF

# Health check interval in seconds
health_check_interval: ${HEALTH_CHECK_INTERVAL}

# Request timeout in seconds
timeout: ${TIMEOUT}

# Routing strategy: "round_robin" or "random"
routing_strategy: ${ROUTING_STRATEGY}
EOF

echo "✓ Generated config.yaml with ${#SERVERS[@]} workers:"
for server in "${SERVERS[@]}"; do
    echo "  - ${PROTOCOL}://${server}:${PORT}"
done
echo

# ============================================================================
# Start Router
# ============================================================================

echo "Starting SandboxFusion Router on ${ROUTER_HOST}:${ROUTER_PORT}..."
uv run uvicorn router:app --host "${ROUTER_HOST}" --port "${ROUTER_PORT}"
